"""
Neo4J Cypher Generator for TestDataGen (#54)

Produces Neo4j Cypher scripts from a parsed TestDataGen schema.

The generator reuses the same data generation pipeline as the SQL and JSON
generators. Generated entity instances become Neo4J nodes, while reference
fields (`ref Entity`) and array references (`ref Entity[]`) are translated
into graph relationships.

Output structure
----------------

//
// Generated by TestDataGen for Neo4J
// Schema: Ecommerce
// Seed: 12345
//

CREATE (:User {id: "...", name: "John"});
CREATE (:Product {id: "...", name: "Chair"});

MATCH (a:Order {id: "..."}), (b:User {id: "..."})
CREATE (a)-[:USER]->(b);

MATCH (a:Order {id: "..."}), (b:Product {id: "..."})
CREATE (a)-[:ITEMS]->(b);

"""

from __future__ import annotations

import os
import random as _random_module
from datetime import date, datetime
from typing import Any, Dict, List, Optional
import json

from testdatagen.generators.faker_integration import FakerTypeMapper

from testdatagen.generators.sql_generator import (
    _topological_sort,
    _collect_strategy_values,
    _combine_and_pad,
    _include_to_row,
    _generate_count,
    _combination_strategy,
    _include_cases,
    _field_type_name,
    _is_array_ref,
    _is_simple_ref,
    _requires_unique_generation,
    _schema_entities,
)


def _schema_relationships(schema):
    return [
        r for r in schema.elements
        if r.__class__.__name__ == "Relationship"
    ]


# ---------------------------------------------------------------------------
# Neo4J value formatting
# ---------------------------------------------------------------------------


def format_value_neo4j(value: Any) -> str:
    """
    Convert a Python value into a Cypher literal.

    Rules
    -----
    None        -> null
    bool        -> true / false
    int, float  -> number
    date        -> "YYYY-MM-DD"
    datetime    -> "YYYY-MM-DDTHH:MM:SS"
    str         -> quoted string
    list        -> [ ... ]
    """
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, datetime):
        return json.dumps(value.isoformat(), ensure_ascii=False)
    if isinstance(value, date):
        return json.dumps(value.isoformat(), ensure_ascii=False)
    if isinstance(value, list):
        return "[" + ", ".join(
            format_value_neo4j(v)
            for v in value
        ) + "]"
    return json.dumps(str(value), ensure_ascii=False)


# ---------------------------------------------------------------------------
# Main generator class
# ---------------------------------------------------------------------------

class Neo4JGenerator:
    """
    Generates Neo4J Cypher scripts from a TestDataGen schema model.

    Parameters
    ----------
    model       : parsed textX model (from grammar_loader.load_model)
    seed        : override seed (None -> use schema seed or random)
    timestamp   : generation timestamp embedded in script comments
    """

    def __init__(
        self,
        model,
        seed: Optional[int] = None,
        timestamp: str = "",
    ):
        self.model = model
        self.seed = seed if seed is not None else getattr(model, "seed", None)
        self.timestamp = timestamp

        self._mapper = FakerTypeMapper(seed=self.seed)
        self._generated_ids: Dict[str, List[Any]] = {}

    # ------------------------------------------------------------------
    # Public
    # ------------------------------------------------------------------

    def render(self) -> str:
        """Return the complete Cypher script."""
        data = self.build()
        return self._render_cypher(data)

    def build(self) -> dict:
        """
        Build an intermediate representation of Neo4J nodes and
        relationships before rendering to Cypher.
        """
        schema = self.model
        entities = _topological_sort(list(_schema_entities(schema)))
        global_strategy = getattr(schema, "strategy", "random") or "random"
        global_combo = getattr(schema, "combination_strategy", "pairwise") or "pairwise"

        nodes = []
        relationships = []

        for entity in entities:
            config = getattr(entity, "config", None)
            generate = _generate_count(config)
            combo_strat = _combination_strategy(config, global_combo)
            includes = _include_cases(config)

            normal_fields = [f for f in entity.fields if not _is_array_ref(f)]
            array_fields = [f for f in entity.fields if _is_array_ref(f)]

            combo_fields = [
                f for f in normal_fields
                if not _requires_unique_generation(f)
            ]
            unique_fields = [
                f for f in normal_fields
                if _requires_unique_generation(f)
            ]
            field_values = {
                field.name: _collect_strategy_values(
                    field,
                    global_strategy,
                    self._mapper,
                    generate,
                )
                for field in combo_fields
            }
            rows = _combine_and_pad(
                field_values,
                combo_strat,
                self.seed,
                generate,
            )
            include_rows = [
                _include_to_row(tc, entity.fields)
                for tc in includes
            ]
            rows = (include_rows + rows)[:generate]
            for row in rows:
                for field in unique_fields:
                    if row.get(field.name) is None:
                        row[field.name] = self._mapper.generate_for_type_name(
                            _field_type_name(field.type),
                            field.constraints,
                        )

            rows = self._resolve_refs(rows, normal_fields)
            self._store_ids(entity, rows)
            if array_fields:
                rows = self._attach_array_refs(
                    entity,
                    array_fields,
                    rows,
                )
            nodes.extend(
                self._build_nodes(entity, rows)
            )

        return {
            "metadata": {
                "schema": getattr(schema, "name", "Unknown"),
                "seed": self.seed,
                "generated_at": self.timestamp,
            },
            "nodes": nodes,
            "relationships": relationships,
        }

    # ------------------------------------------------------------------
    # Internal helpers (mirror sql_generator internals)
    # ------------------------------------------------------------------

    def _store_ids(self, entity, rows: List[Dict[str, Any]]):
        """Remember generated IDs so later entities can reference them."""
        id_field = None
        for field in entity.fields:
            if field.name == "id":
                id_field = "id"
                break

        if id_field is None:
            for field in entity.fields:
                if _field_type_name(field.type) == "uuid":
                    id_field = field.name
                    break

        if id_field is None and entity.fields:
            id_field = entity.fields[0].name

        if id_field:
            self._generated_ids[entity.name] = [
                row.get(id_field)
                for row in rows
                if row.get(id_field) is not None
            ]

    def _resolve_refs(
        self,
        rows: List[Dict[str, Any]],
        fields,
    ) -> List[Dict[str, Any]]:
        """Replace __ref__ placeholders with generated IDs."""
        rng = _random_module.Random(self.seed)
        ref_fields = {
            field.name: field
            for field in fields
            if _is_simple_ref(field)
        }
        if not ref_fields:
            return rows

        resolved = []
        for row in rows:
            new_row = dict(row)
            for field_name, field in ref_fields.items():
                if new_row.get(field_name) == "__ref__":
                    ref_entity = field.type.entity.name
                    ids = self._generated_ids.get(ref_entity, [])
                    new_row[field_name] = rng.choice(ids) if ids else None
            resolved.append(new_row)
        return resolved

    def _attach_array_refs(
        self,
        entity,
        array_fields,
        rows: List[Dict[str, Any]],
    ) -> List[Dict[str, Any]]:
        """
        Replace array reference placeholders with lists of generated IDs.
        """
        rng = _random_module.Random(self.seed)
        for field in array_fields:
            ref_entity = field.type.entity.name
            available_ids = self._generated_ids.get(ref_entity, [])
            if not available_ids:
                for row in rows:
                    row[field.name] = []
                continue

            field_type = field.type

            has_count = bool(getattr(field_type, "has_count", False))
            min_count = getattr(field_type, "min", 1) if has_count else 1
            max_count = getattr(field_type, "max", 3) if has_count else 3

            for row in rows:
                count = rng.randint(min_count, max_count)
                row[field.name] = rng.choices(
                    available_ids,
                    k=count,
                )
        return rows

    def _build_nodes(self, entity, rows):
        nodes = []
        for row in rows:
            properties = {}
            for field in entity.fields:
                if _is_simple_ref(field) or _is_array_ref(field):
                    continue
                properties[field.name] = row.get(field.name)
            nodes.append({
                "label": entity.name,
                "properties": properties,
            })
        return nodes

    def _build_relationships(
        self,
        entity,
        normal_fields,
        array_fields,
        rows,
    ):
        """Build Neo4J relationship definitions."""
        relationships = []
        for row in rows:
            source_id = row.get("id")

            if source_id is None:
                continue

            for field in normal_fields:
                if not _is_simple_ref(field):
                    continue
                target = row.get(field.name)

                if target is None:
                    continue
                relationships.append({
                    "from_label": entity.name,
                    "from_id": source_id,
                    "to_label": field.type.entity.name,
                    "to_id": target,
                    "type": field.name.upper(),
                })

            for field in array_fields:
                targets = row.get(field.name, [])
                for target in targets:
                    relationships.append({
                        "from_label": entity.name,
                        "from_id": source_id,
                        "to_label": field.type.entity.name,
                        "to_id": target,
                        "type": field.name.upper(),
                    })

        return relationships
    
    def _render_cypher(self, data: Dict[str, Any]) -> str:
        """
        Render the generated graph data as a Neo4J Cypher script.
        """
        lines = [
            "// =========================================================",
            "// Generated by TestDataGen for Neo4J",
            f"// Schema: {data['metadata']['schema']}",
            f"// Seed: {data['metadata']['seed']}",
            f"// Generated at: {data['metadata']['generated_at']}",
            "// =========================================================",
            "",
            "// --- Node Definitions ---",
        ]

        # ----------------------------------------------------------
        # Node definitions
        # ----------------------------------------------------------
        for node in data["nodes"]:
            label = node["label"]
            properties = node["properties"]

            props = [
                f"{key}: {format_value_neo4j(value)}"
                for key, value in properties.items()
            ]

            lines.append(
                f"CREATE (:{label} {{{', '.join(props)}}});"
            )

        # ----------------------------------------------------------
        # Relationship definitions
        # ----------------------------------------------------------
        lines.extend([
            "",
            "// --- Relationship Definitions ---",
        ])

        for relationship in data["relationships"]:
            lines.extend([
                (
                    f"MATCH (from:{relationship['from_label']} "
                    f"{{id: {format_value_neo4j(relationship['from_id'])}}}), "
                    f"(to:{relationship['to_label']} "
                    f"{{id: {format_value_neo4j(relationship['to_id'])}}})"
                ),
                f"CREATE (from)-[:{relationship['type']}]->(to);",
                "",
            ])

        return "\n".join(lines)


def generate_neo4j(model, output_dir, overwrite):
    """
    CLI interface for the Neo4JGenerator class.
    Handles file I/O and orchestration.
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    generator = Neo4JGenerator(
        model,
        timestamp=timestamp,
    )
    cypher = generator.render()
    schema_name = getattr(model, "name", "generated_data")
    file_path = os.path.join(
        output_dir,
        f"{schema_name}.cypher",
    )
    if os.path.exists(file_path) and not overwrite:
        raise FileExistsError(
            f"File {file_path} already exists. Use --overwrite to replace it."
        )
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(cypher)
    return file_path
