"""
Neo4J Cypher Generator for TestDataGen (#54)

Produces Neo4j Cypher scripts from a parsed TestDataGen schema.

The generator reuses the same data generation pipeline as the SQL and JSON
generators. Generated entity instances become Neo4J nodes, while reference
fields (`ref Entity`) and array references (`ref Entity[]`) are translated
into graph relationships.

Output structure
----------------

//
// Generated by TestDataGen for Neo4J
// Schema: Ecommerce
// Seed: 12345
//

CREATE (:User {id: "...", name: "John"});
CREATE (:Product {id: "...", name: "Chair"});

MATCH (a:Order {id: "..."}), (b:User {id: "..."})
CREATE (a)-[:USER]->(b);

MATCH (a:Order {id: "..."}), (b:Product {id: "..."})
CREATE (a)-[:ITEMS]->(b);

"""

from __future__ import annotations

import os
import random as _random_module
from datetime import date, datetime
from typing import Any, Dict, List, Optional
import json

from testdatagen.generators.faker_integration import FakerTypeMapper

from testdatagen.generators.sql_generator import (
    _topological_sort,
    _collect_strategy_values,
    _combine_and_pad,
    _include_to_row,
    _generate_count,
    _combination_strategy,
    _include_cases,
    _field_type_name,
    _is_array_ref,
    _is_simple_ref,
    _requires_unique_generation,
    _schema_entities,
)

from testdatagen.strategies.relationships import (
    _one_to_one,
    _one_to_many,
    _many_to_one,
    _many_to_many
)


def _schema_relationships(schema):
    return [
        r for r in schema.elements
        if r.__class__.__name__ == "Relationship"
    ]


# ---------------------------------------------------------------------------
# Neo4J value formatting
# ---------------------------------------------------------------------------


def format_value_neo4j(value: Any) -> str:
    """
    Convert a Python value into a Cypher literal.

    Rules
    -----
    None        -> null
    bool        -> true / false
    int, float  -> number
    date        -> "YYYY-MM-DD"
    datetime    -> "YYYY-MM-DDTHH:MM:SS"
    str         -> quoted string
    list        -> [ ... ]
    """
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, datetime):
        return json.dumps(value.isoformat(), ensure_ascii=False)
    if isinstance(value, date):
        return json.dumps(value.isoformat(), ensure_ascii=False)
    if isinstance(value, list):
        return "[" + ", ".join(
            format_value_neo4j(v)
            for v in value
        ) + "]"
    return json.dumps(str(value), ensure_ascii=False)


# ---------------------------------------------------------------------------
# Main generator class
# ---------------------------------------------------------------------------

class Neo4JGenerator:
    """
    Generates Neo4J Cypher scripts from a TestDataGen schema model.

    Parameters
    ----------
    model       : parsed textX model (from grammar_loader.load_model)
    seed        : override seed (None -> use schema seed or random)
    timestamp   : generation timestamp embedded in script comments
    """

    def __init__(
        self,
        model,
        seed: Optional[int] = None,
        timestamp: str = "",
    ):
        self.model = model
        self.seed = seed if seed is not None else getattr(model, "seed", None)
        self.timestamp = timestamp

        self._mapper = FakerTypeMapper(seed=self.seed)
        self._generated_ids: Dict[str, List[Any]] = {}
        self._generated_rows: Dict[str, List[Dict[str, Any]]] = {}

    # ------------------------------------------------------------------
    # Public
    # ------------------------------------------------------------------

    def render(self) -> str:
        """Return the complete Cypher script."""
        data = self.build()
        return self._render_cypher(data)


    def build(self):
        schema = self.model

        entities = _topological_sort(
            list(_schema_entities(schema))
        )

        nodes_list = list(self._node_stream(entities))

        relationships_list = list(self._relationship_stream(schema))

        return {
            "metadata": {
                "schema": getattr(schema, "name", "Unknown"),
                "seed": self.seed,
                "generated_at": self.timestamp,
            },
            "nodes": nodes_list,
            "relationships": relationships_list,
        }


    def _node_stream(self, entities):
        global_strategy = getattr(self.model, "strategy", "random") or "random"
        global_combo = getattr(
            self.model,
            "combination_strategy",
            "pairwise",
        ) or "pairwise"

        for entity in entities:

            config = getattr(entity, "config", None)
            generate = _generate_count(config)
            combo_strat = _combination_strategy(config, global_combo)
            includes = _include_cases(config)

            normal_fields = [
                f for f in entity.fields
                if not _is_simple_ref(f) and not _is_array_ref(f)
            ]

            combo_fields = [
                f for f in normal_fields
                if not _requires_unique_generation(f)
            ]

            unique_fields = [
                f for f in normal_fields
                if _requires_unique_generation(f)
            ]

            field_values = {
                field.name: _collect_strategy_values(
                    field,
                    global_strategy,
                    self._mapper,
                    generate,
                )
                for field in combo_fields
            }

            rows = _combine_and_pad(
                field_values,
                combo_strat,
                self.seed,
                generate,
            )

            include_rows = [
                _include_to_row(tc, entity.fields)
                for tc in includes
            ]

            rows = (include_rows + rows)[:generate]

            for row in rows:
                for field in unique_fields:
                    if row.get(field.name) is None:
                        row[field.name] = self._mapper.generate_for_type_name(
                            _field_type_name(field.type),
                            field.constraints,
                        )

            self._store_ids(entity, rows)
            self._generated_rows[entity.name] = rows

            yield from self._build_nodes(entity, rows)


    def _generate_relationship_rows(self, relationship):
        """Generiše redove podataka za properties relacije koristeći isti pipeline kao i entiteti."""
        properties_def = getattr(relationship, "properties", None)
        if not properties_def:
            return []

        config = getattr(relationship, "config", None)
        global_strategy = getattr(self.model, "strategy", "random") or "random"
        global_combo = getattr(self.model, "combination_strategy", "pairwise") or "pairwise"

        generate = _generate_count(config)

        combo_strat = _combination_strategy(config, global_combo)
        includes = _include_cases(config)

        normal_fields = [
            f for f in properties_def
            if not _is_simple_ref(f) and not _is_array_ref(f)
        ]

        combo_fields = [
            f for f in normal_fields
            if not _requires_unique_generation(f)
        ]

        unique_fields = [
            f for f in normal_fields
            if _requires_unique_generation(f)
        ]

        field_values = {
            field.name: _collect_strategy_values(
                field,
                global_strategy,
                self._mapper,
                generate,
            )
            for field in combo_fields
        }

        rows = _combine_and_pad(
            field_values,
            combo_strat,
            self.seed,
            generate,
        )

        include_rows = [
            _include_to_row(tc, properties_def)
            for tc in includes
        ]

        rows = (include_rows + rows)[:generate]

        for row in rows:
            for field in unique_fields:
                if row.get(field.name) is None:
                    row[field.name] = self._mapper.generate_for_type_name(
                        _field_type_name(field.type),
                        field.constraints,
                    )

        return rows

        
    def _relationship_stream(self, schema):
        for relationship in _schema_relationships(schema):
            yield from self._build_relationships(relationship)


    # ------------------------------------------------------------------
    # Internal helpers (mirror sql_generator internals)
    # ------------------------------------------------------------------

    def _store_ids(self, entity, rows: List[Dict[str, Any]]):
        """Remember generated IDs so later entities can reference them."""
        id_field = None
        for field in entity.fields:
            if field.name == "id":
                id_field = "id"
                break

        if id_field is None:
            for field in entity.fields:
                if _field_type_name(field.type) == "uuid":
                    id_field = field.name
                    break

        if id_field is None and entity.fields:
            id_field = entity.fields[0].name

        if id_field:
            self._generated_ids[entity.name] = [
                row.get(id_field)
                for row in rows
                if row.get(id_field) is not None
            ]


    def _build_nodes(self, entity, rows):
        for row in rows:

            properties = {}

            for field in entity.fields:
                if _is_simple_ref(field) or _is_array_ref(field):
                    continue

                properties[field.name] = row.get(field.name)

            yield {
                "label": entity.name,
                "properties": properties,
            }

    def _build_relationships(self, relationship):
        options = self._relationship_options(
            getattr(relationship, "config", None)
        )

        strategy = options["strategy"]
        
        from_obj = getattr(relationship, "from_", getattr(relationship, "from", None))
        from_name = from_obj.name if from_obj else None

        from_rows = self._generated_rows.get(from_name, [])
        to_rows = self._generated_rows.get(relationship.to.name, [])

        if not from_rows or not to_rows:
            return iter(())

        # Generišemo redove za properties relacije
        prop_rows = self._generate_relationship_rows(relationship)

        kwargs = dict(
            relationship=relationship,
            from_rows=from_rows,
            to_rows=to_rows,
            prop_rows=prop_rows,  # <--- Prosleđujemo redove svojstava
            generate=options["generate"],
            min_degree=options["min_degree"],
            max_degree=options["max_degree"],
            seed=self.seed,
        )

        if strategy == "one-to-one":
            return _one_to_one(**kwargs)

        if strategy == "one-to-many":
            return _one_to_many(**kwargs)

        if strategy == "many-to-one":
            return _many_to_one(**kwargs)

        if strategy == "many-to-many":
            return _many_to_many(**kwargs)

        return _one_to_one(**kwargs)


    def _relationship_options(self, config):
        strategy = "one-to-one"
        min_degree = 1
        max_degree = None
        generate = _generate_count(config)

        if config:
            for option in config.options:
                if option.__class__.__name__ == "RelationshipStrategyOption":
                    strategy = option.strategy

                elif option.__class__.__name__ == "MinDegreeOption":
                    min_degree = option.value

                elif option.__class__.__name__ == "MaxDegreeOption":
                    max_degree = option.value

        return {
            "strategy": strategy,
            "min_degree": min_degree,
            "max_degree": max_degree,
            "generate": generate,
        }
    
    def _render_cypher(self, data: Dict[str, Any]) -> str:
        """
        Render the generated graph data as a Neo4J Cypher script.
        """
        lines = [
            "// =========================================================",
            "// Generated by TestDataGen for Neo4J",
            f"// Schema: {data['metadata']['schema']}",
            f"// Seed: {data['metadata']['seed']}",
            f"// Generated at: {data['metadata']['generated_at']}",
            "// =========================================================",
            "",
            "// --- Node Definitions ---",
        ]

        # ----------------------------------------------------------
        # Node definitions
        # ----------------------------------------------------------
        for node in data["nodes"]:
            label = node["label"]
            properties = node["properties"]

            props = [
                f"{key}: {format_value_neo4j(value)}"
                for key, value in properties.items()
            ]

            lines.append(
                f"CREATE (:{label} {{{', '.join(props)}}});"
            )

        # ----------------------------------------------------------
        # Relationship definitions
        # ----------------------------------------------------------
        lines.extend([
            "",
            "// --- Relationship Definitions ---",
        ])

        for relationship in data["relationships"]:
            props = [
                f"{key}: {format_value_neo4j(value)}"
                for key, value in relationship['properties'].items()
            ]
            props_str = f" {{{', '.join(props)}}}" if props else ""

            lines.extend([
                (
                    f"MATCH (from:{relationship['from_label']} "
                    f"{{id: {format_value_neo4j(relationship['from_id'])}}}), "
                    f"(to:{relationship['to_label']} "
                    f"{{id: {format_value_neo4j(relationship['to_id'])}}})"
                ),
                f"CREATE (from)-[:{relationship['type']}{props_str}]->(to);",
                "",
            ])

        return "\n".join(lines)


def generate_neo4j(model, output_dir, overwrite):
    """
    CLI interface for the Neo4JGenerator class.
    Handles file I/O and orchestration.
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    generator = Neo4JGenerator(
        model,
        timestamp=timestamp,
    )
    cypher = generator.render()
    schema_name = getattr(model, "name", "generated_data")
    file_path = os.path.join(
        output_dir,
        f"{schema_name}.cypher",
    )
    if os.path.exists(file_path) and not overwrite:
        raise FileExistsError(
            f"File {file_path} already exists. Use --overwrite to replace it."
        )
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(cypher)
    return file_path
