"""
SQL Generator for TestDataGen (#15)

Produces PostgreSQL INSERT statements from a parsed TestDataGen schema.

Pipeline per entity
-------------------
1. Topological sort  — referenced entities are generated first
2. Collect values    — strategy engine produces candidate value lists per field
3. Combine rows      — full / pairwise / each-used turns value lists into rows
4. Pad rows          — if combination produces fewer than generate, fill with random picks
5. Apply includes    — explicit test-cases from config.include are prepended
6. Resolve FK refs   — __ref__ sentinels are replaced with real IDs
7. Format values     — Python → SQL literal (quotes, NULL, TRUE/FALSE, …)
8. Render template   — Jinja2 produces the final .sql text
"""

from __future__ import annotations

import random as _random_module
from datetime import date, datetime
from typing import Any, Dict, List, Optional

from jinja2 import Environment, BaseLoader

from testdatagen.generators.faker_integration import FakerTypeMapper
from testdatagen.strategies.boundary import generate_boundary_values
from testdatagen.strategies.partition import generate_partition_values, generate_enum_partition_values
from testdatagen.strategies.edge_cases import generate_edge_cases, generate_enum_coverage
from testdatagen.strategies.combination import (
    full_combination,
    each_used_combination,
    pairwise_combination,
)

# ---------------------------------------------------------------------------
# Jinja2 template
# ---------------------------------------------------------------------------

_SQL_TEMPLATE = """\
-- Generated by TestDataGen
-- Schema: {{ schema_name }}
-- Strategy: {{ strategy }}
-- Seed: {{ seed }}
-- Generated at: {{ timestamp }}
{% for entity in entities %}

-- {{ entity.name }} ({{ entity.records|length }} records)
INSERT INTO {{ entity.table_name }} ({{ entity.columns|join(', ') }}) VALUES
{% for record in entity.records %}
({{ record|join(', ') }}){% if not loop.last %},{% endif %}

{% endfor %};
{% endfor %}
{% for jt in junction_tables %}

-- {{ jt.name }} (junction table, {{ jt.records|length }} records)
INSERT INTO {{ jt.name }} ({{ jt.columns|join(', ') }}) VALUES
{% for record in jt.records %}
({{ record|join(', ') }}){% if not loop.last %},{% endif %}

{% endfor %};
{% endfor %}
"""

# ---------------------------------------------------------------------------
# Config option helpers  (options is a flat list, differentiated by class name)
# ---------------------------------------------------------------------------

def _get_option(config, class_name):
    if config is None:
        return None
    for opt in getattr(config, "options", []):
        if opt.__class__.__name__ == class_name:
            return opt
    return None


def _generate_count(config) -> int:
    opt = _get_option(config, "GenerateOption")
    return opt.generate if opt else 10


def _combination_strategy(config, schema_default: str) -> str:
    opt = _get_option(config, "EntityCombinationStrategyOption")
    if opt and getattr(opt, "combination_strategy", None):
        return opt.combination_strategy
    return schema_default or "pairwise"


def _include_cases(config) -> list:
    opt = _get_option(config, "IncludeOption")
    return opt.include if opt else []


# ---------------------------------------------------------------------------
# Field-level helpers
# ---------------------------------------------------------------------------

def _field_type_name(field_type) -> str:
    cn = field_type.__class__.__name__
    if cn == "RefType":
        return "ref"
    if cn == "EnumType":
        return "enum"
    if hasattr(field_type, "name"):
        return field_type.name
    return cn


def _get_constraint(constraints, class_name):
    for c in constraints or []:
        if c.__class__.__name__ == class_name:
            return c
    return None


def _is_array_ref(field) -> bool:
    return (
        field.type.__class__.__name__ == "RefType"
        and bool(getattr(field.type, "array", False))
    )


def _is_simple_ref(field) -> bool:
    return (
        field.type.__class__.__name__ == "RefType"
        and not bool(getattr(field.type, "array", False))
    )


# ---------------------------------------------------------------------------
# SQL value formatting
# ---------------------------------------------------------------------------

def _escape_string(s: str) -> str:
    """Escape single quotes for PostgreSQL string literals."""
    return s.replace("'", "''")


def format_value(value: Any) -> str:
    """
    Convert a Python value to a SQL literal string.

    Rules
    -----
    None            → NULL
    bool            → TRUE / FALSE   (must come before int — bool is a subclass of int)
    int / float     → bare number
    str             → 'escaped string'
    date / datetime → 'YYYY-MM-DD' / 'YYYY-MM-DDTHH:MM:SS'
    """
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, datetime):
        return f"'{value.isoformat()}'"
    if isinstance(value, date):
        return f"'{value.isoformat()}'"
    if isinstance(value, str):
        return f"'{_escape_string(value)}'"
    # fallback
    return f"'{_escape_string(str(value))}'"


# ---------------------------------------------------------------------------
# Topological sort (Kahn's algorithm)
# ---------------------------------------------------------------------------

def _topological_sort(entities) -> List:
    """
    Return entities ordered so that every referenced entity comes before
    the entity that references it.
    """
    name_to_entity = {e.name: e for e in entities}

    in_degree: Dict[str, int] = {e.name: 0 for e in entities}
    reverse: Dict[str, List[str]] = {e.name: [] for e in entities}

    for entity in entities:
        for field in entity.fields:
            if field.type.__class__.__name__ == "RefType":
                ref_name = field.type.entity.name
                if ref_name != entity.name:      # skip self-refs
                    in_degree[entity.name] += 1
                    reverse[ref_name].append(entity.name)

    queue = sorted([name for name, deg in in_degree.items() if deg == 0])
    order = []

    while queue:
        node = queue.pop(0)
        order.append(node)
        for dependent in sorted(reverse[node]):
            in_degree[dependent] -= 1
            if in_degree[dependent] == 0:
                queue.append(dependent)

    # Any remaining nodes are part of a cycle — append them as-is
    remaining = [name for name in in_degree if name not in order]
    order.extend(remaining)

    return [name_to_entity[name] for name in order]


# ---------------------------------------------------------------------------
# Value collection from strategy engine
# ---------------------------------------------------------------------------

def _collect_strategy_values(field, global_strategy: str, mapper: FakerTypeMapper) -> List[Any]:
    """
    Produce the list of candidate values for one field by consulting the
    strategy engine.  Returns a non-empty list in all cases.
    """
    ft_name = _field_type_name(field.type)
    constraints = list(getattr(field, "constraints", []) or [])

    sc = _get_constraint(constraints, "StrategyConstraint")
    field_strategy = sc.value if sc else global_strategy

    boundary_c   = _get_constraint(constraints, "BoundaryConstraint")
    partition_c  = _get_constraint(constraints, "PartitionConstraint")
    partitions_c = _get_constraint(constraints, "PartitionsConstraint")
    range_c      = _get_constraint(constraints, "RangeConstraint")
    include_c    = _get_constraint(constraints, "IncludeConstraint")
    special_c    = _get_constraint(constraints, "SpecialConstraint")
    precision_c  = _get_constraint(constraints, "PrecisionConstraint")
    precision    = precision_c.value if precision_c else 0

    values: List[Any] = []

    # --- Enum ---
    if ft_name == "enum":
        enum_vals = list(field.type.values)
        if field_strategy in ("smart", "partition"):
            values += [r["value"] for r in generate_enum_partition_values(enum_vals)]
        if field_strategy == "smart":
            values += [r["value"] for r in generate_enum_coverage(enum_vals)]
        if not values:
            values = list(enum_vals)
        if include_c:
            edge = generate_edge_cases(ft_name, include_values=list(include_c.values))
            values += [r["value"] for r in edge]
        return _deduplicate(values) or list(enum_vals)

    # --- Ref ---
    if ft_name == "ref":
        return ["__ref__"]

    # --- Boolean ---
    if ft_name == "boolean":
        vals = [True, False]
        if include_c and "null" in list(include_c.values):
            vals.append(None)
        return vals

    # --- Number / Date / Datetime ---
    if ft_name in ("number", "date", "datetime"):
        min_val = range_c.min if range_c else None
        max_val = range_c.max if range_c else None

        use_boundary  = field_strategy in ("smart", "boundary") or boundary_c is not None
        use_partition = field_strategy in ("smart", "partition") or partition_c is not None or partitions_c is not None

        if use_boundary and min_val is not None:
            bv = generate_boundary_values(ft_name, min_val, max_val, precision=precision)
            values += [r["value"] for r in bv if r["category"] == "valid"]

        if use_partition and min_val is not None:
            if partitions_c:
                values += list(partitions_c.values)
            elif partition_c:
                pv = generate_partition_values(ft_name, min_val, max_val,
                                               num_partitions=partition_c.value,
                                               precision=precision)
                values += [r["value"] for r in pv]
            else:
                pv = generate_partition_values(ft_name, min_val, max_val, precision=precision)
                values += [r["value"] for r in pv]

        if special_c:
            values += list(special_c.values)
        if include_c:
            edge = generate_edge_cases(ft_name, include_values=list(include_c.values))
            values += [r["value"] for r in edge]
        if not values:
            values = [mapper.generate_for_type_name(ft_name, constraints)]

        return _deduplicate(values)

    # --- String-like types ---
    edge_values: List[Any] = []
    if include_c:
        edge = generate_edge_cases(ft_name, include_values=list(include_c.values))
        edge_values = [r["value"] for r in edge]
    if special_c:
        edge_values += list(special_c.values)

    faker_val = mapper.generate_for_type_name(ft_name, constraints)
    return _deduplicate([faker_val] + edge_values) or [faker_val]


def _deduplicate(values: List[Any]) -> List[Any]:
    """Remove duplicates preserving order. None is a valid value."""
    seen = []
    result = []
    for v in values:
        key = (type(v), v)
        if key not in seen:
            seen.append(key)
            result.append(v)
    return result


# ---------------------------------------------------------------------------
# Row combination + padding
# ---------------------------------------------------------------------------

def _combine_and_pad(
    field_values: Dict[str, List[Any]],
    strategy: str,
    seed: Optional[int],
    generate: int,
) -> List[Dict[str, Any]]:
    """
    Apply the chosen combination strategy, then pad with random rows up to
    *generate* count if the strategy produced fewer rows.
    """
    if not field_values:
        return []

    if strategy == "full":
        rows = list(full_combination(field_values, limit=generate))
    elif strategy == "each-used":
        rows = each_used_combination(field_values, seed=seed)
    else:   # pairwise (default)
        rows = pairwise_combination(field_values, seed=seed)

    # Pad up to generate count with random picks from each field's value list
    if len(rows) < generate:
        rng = _random_module.Random(seed)
        while len(rows) < generate:
            rows.append({fname: rng.choice(vals) for fname, vals in field_values.items()})

    return rows[:generate] if generate else rows


# ---------------------------------------------------------------------------
# Include (explicit test cases) → row dicts
# ---------------------------------------------------------------------------

def _include_to_row(test_case, entity_fields) -> Dict[str, Any]:
    """
    Convert a textX TestCase (list of FieldAssignments) to a plain dict.
    Fields not mentioned in the test case are filled with None.
    """
    row = {f.name: None for f in entity_fields}
    for assignment in test_case.assignments:
        raw = assignment.value
        row[assignment.name] = None if (raw == "null" or raw is None) else raw
    return row


# ---------------------------------------------------------------------------
# Main generator class
# ---------------------------------------------------------------------------

class SQLGenerator:
    """
    Generates PostgreSQL INSERT statements from a TestDataGen schema model.

    Parameters
    ----------
    model     : parsed textX model (from grammar_loader.load_model)
    seed      : override seed (None → use schema seed or random)
    timestamp : string to embed in the header comment
    """

    def __init__(self, model, seed: Optional[int] = None, timestamp: str = ""):
        self.model     = model
        self.seed      = seed if seed is not None else getattr(model, "seed", None)
        self.timestamp = timestamp
        self._mapper   = FakerTypeMapper(seed=self.seed)
        self._generated_ids: Dict[str, List[Any]] = {}

    # ------------------------------------------------------------------
    # Public
    # ------------------------------------------------------------------

    def render(self) -> str:
        """Return the complete SQL as a string."""
        schema          = self.model
        entities        = _topological_sort(list(schema.entities))
        global_strategy = getattr(schema, "strategy", "random") or "random"
        global_combo    = getattr(schema, "combination_strategy", "pairwise") or "pairwise"

        entity_data  = []
        junction_data = []

        for entity in entities:
            config      = getattr(entity, "config", None)
            generate    = _generate_count(config)
            combo_strat = _combination_strategy(config, global_combo)
            includes    = _include_cases(config)

            normal_fields = [f for f in entity.fields if not _is_array_ref(f)]
            array_fields  = [f for f in entity.fields if _is_array_ref(f)]

            # 1. Collect strategy values
            field_values: Dict[str, List[Any]] = {
                field.name: _collect_strategy_values(field, global_strategy, self._mapper)
                for field in normal_fields
            }

            # 2. Combine + pad to generate count
            rows = _combine_and_pad(field_values, combo_strat, self.seed, generate)

            # 3. Prepend explicit include test cases, then trim to generate
            include_rows = [_include_to_row(tc, entity.fields) for tc in includes]
            rows = (include_rows + rows)[:generate]

            # 4. Resolve FK refs
            rows = self._resolve_refs(rows, normal_fields)

            # 5. Track IDs for downstream FK resolution
            self._store_ids(entity, rows)

            # 6. Junction table rows for array-ref fields
            for arr_field in array_fields:
                jt_rows = self._build_junction_rows(entity, arr_field, rows)
                if jt_rows:
                    ref_entity_name = arr_field.type.entity.name.lower()
                    jt_name    = f"{entity.name.lower()}s_{ref_entity_name}s"
                    entity_col = f"{entity.name.lower()}_id"
                    ref_col    = f"{ref_entity_name}_id"
                    junction_data.append({
                        "name":    jt_name,
                        "columns": [entity_col, ref_col],
                        "records": [
                            [format_value(r[entity_col]), format_value(r[ref_col])]
                            for r in jt_rows
                        ],
                    })

            # 7. Format for template
            columns = [f.name for f in normal_fields]
            entity_data.append({
                "name":       entity.name,
                "table_name": entity.name.lower() + "s",
                "columns":    columns,
                "records":    [
                    [format_value(row.get(col)) for col in columns]
                    for row in rows
                ],
            })

        env  = Environment(loader=BaseLoader())
        tmpl = env.from_string(_SQL_TEMPLATE)
        return tmpl.render(
            schema_name     = getattr(schema, "name", "Unknown"),
            strategy        = getattr(schema, "strategy", "random") or "random",
            seed            = self.seed if self.seed is not None else "none",
            timestamp       = self.timestamp,
            entities        = entity_data,
            junction_tables = junction_data,
        )

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _store_ids(self, entity, rows: List[Dict[str, Any]]):
        """Remember the generated id values so later entities can use them as FKs."""
        id_field = None
        for f in entity.fields:
            if f.name == "id":
                id_field = "id"
                break
        if id_field is None:
            for f in entity.fields:
                if _field_type_name(f.type) == "uuid":
                    id_field = f.name
                    break
        if id_field is None and entity.fields:
            id_field = entity.fields[0].name

        if id_field:
            self._generated_ids[entity.name] = [
                row.get(id_field) for row in rows if row.get(id_field) is not None
            ]

    def _resolve_refs(self, rows: List[Dict[str, Any]], fields) -> List[Dict[str, Any]]:
        """Replace __ref__ sentinels with actual FK values from already-generated entities."""
        rng = _random_module.Random(self.seed)
        ref_fields = {f.name: f for f in fields if _is_simple_ref(f)}
        if not ref_fields:
            return rows

        resolved = []
        for row in rows:
            new_row = dict(row)
            for fname, field in ref_fields.items():
                if new_row.get(fname) == "__ref__":
                    ref_entity_name = field.type.entity.name
                    available = self._generated_ids.get(ref_entity_name, [])
                    new_row[fname] = rng.choice(available) if available else None
            resolved.append(new_row)
        return resolved

    def _build_junction_rows(self, entity, arr_field, entity_rows: List[Dict[str, Any]]) -> List[Dict]:
        """For an array-ref field, generate junction table rows."""
        rng = _random_module.Random(self.seed)

        ref_entity_name = arr_field.type.entity.name
        available_ids   = self._generated_ids.get(ref_entity_name, [])
        if not available_ids:
            return []

        ft        = arr_field.type
        has_count = bool(getattr(ft, "has_count", False))
        min_count = getattr(ft, "min", 1) if has_count else 1
        max_count = getattr(ft, "max", 3) if has_count else 3

        entity_col = f"{entity.name.lower()}_id"
        ref_col    = f"{ref_entity_name.lower()}_id"

        id_field = next((f.name for f in entity.fields if f.name == "id"), None)
        if id_field is None and entity.fields:
            id_field = entity.fields[0].name

        jt_rows = []
        for row in entity_rows:
            entity_id = row.get(id_field)
            if entity_id is None:
                continue
            count = rng.randint(min_count, max_count)
            for ref_id in rng.choices(available_ids, k=count):
                jt_rows.append({entity_col: entity_id, ref_col: ref_id})

        return jt_rows